- name: Demo on variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Print a Variable
      debug:
        msg: "URL = {{URL}}"
## when there is a variable reference (calling variable), Double quote it
        