- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Print a Variable
      debug:
        msg: "URL = {{URL}}"
    - name: Print task Variable
      debug:
        msg: "URL = {{URL}}"
      vars:
        URL: task.google.com
## when there is a variable reference (calling variable), Double quote it
