- name: Demo on tags
  hosts: localhost
  tasks:
    - name: Ubuntu Task
      debug:
        msg: Ubuntu Task
      tags:
        - ubuntu
        - debain

    - name: CentOS task
      debug:
        msg: CentOS Task
      tags:
        - centos
        - redhat


