- name: Demo on when conditions
  hosts: localhost
  vars:
    URL: google.org
  tasks:
    - name: Conditon on strings
      when: URL == "google.com"
      debug:
        msg: Heloo

    - name: Conditon on strings
      when: URL != "google.com"
      debug:
        msg: Heloo