- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop

- name: Download GitHub
  include_tasks:
    file: download.yml

- name: Copy the extracted content
  copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install Catalogue Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
    state: latest
  become_user: roboshop


#    $ npm install
#  NOTE: We need to update the IP address of MONGODB Server in systemd.service file. Replace MONGO_DNSNAME with IP address.
#    Now, lets set up the service with systemctl.
#
#  # mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
#  # systemctl daemon-reload
#  # systemctl start catalogue
#  # systemctl enable catalogue